# Simple Application on Windows Web App
# Package and deploy a simple web application and deploy it to Azure as Windows web app.

on:
  push:
    branches:
      - main

name: Package and deploy simple web app

jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # deploy web app
    - uses: azure/webapps-deploy@v1
      with:
        app-name: aatiwarishub-node-windows
        package: .
        publish-profile: ${{secrets.aatiwarishub_node_windows_f958}}